import { PrismaClient } from '@prisma/client'

export async function seedWorkflowStepLibrary(prisma: PrismaClient) {
  const steps = [
    // ── Generic / universal ───────────────────────────────────────────────
    {
      code: 'PENDING',
      label: 'Pending',
      description: 'Booking submitted, waiting for provider to respond.',
      category: 'generic',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'accept', label: 'Accept', targetStatus: 'confirmed', style: 'primary' },
        { action: 'deny', label: 'Decline', targetStatus: 'cancelled', style: 'danger' },
      ],
      defaultActionsPatient: [
        { action: 'cancel', label: 'Cancel request', targetStatus: 'cancelled', style: 'danger' },
      ],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 10,
    },
    {
      code: 'CONFIRMED',
      label: 'Confirmed',
      description: 'Provider accepted — conversation and video/audio room created automatically.',
      category: 'generic',
      defaultFlags: {},
      defaultActionsProvider: [],
      defaultActionsPatient: [
        { action: 'cancel', label: 'Cancel booking', targetStatus: 'cancelled', style: 'danger' },
      ],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 20,
    },
    {
      code: 'CANCELLED',
      label: 'Cancelled',
      description: 'Booking cancelled by patient or provider.',
      category: 'generic',
      defaultFlags: {},
      defaultActionsProvider: [],
      defaultActionsPatient: [],
      isTerminal: true,
      isCancellation: true,
      sortOrder: 900,
    },
    {
      code: 'COMPLETED',
      label: 'Completed',
      description: 'Service fully delivered. Review request sent automatically.',
      category: 'generic',
      defaultFlags: {},
      defaultActionsProvider: [],
      defaultActionsPatient: [],
      isTerminal: true,
      isCancellation: false,
      sortOrder: 800,
    },

    // ── Video / audio consultation ─────────────────────────────────────────
    {
      code: 'VIDEO_CALL_READY',
      label: 'Video Call Ready',
      description: 'Both sides can now join the video room. Room URL sent via notification.',
      category: 'consultation',
      defaultFlags: { triggers_video_call: true },
      defaultActionsProvider: [
        { action: 'join_call', label: 'Join video call', targetStatus: 'video_call_active', style: 'primary' },
      ],
      defaultActionsPatient: [
        { action: 'join_call', label: 'Join video call', targetStatus: 'video_call_active', style: 'primary' },
      ],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 30,
    },
    {
      code: 'VIDEO_CALL_ACTIVE',
      label: 'In Video Call',
      description: 'Video consultation is in progress.',
      category: 'consultation',
      defaultFlags: { triggers_video_call: true },
      defaultActionsProvider: [
        { action: 'end_call', label: 'End call & write notes', targetStatus: 'writing_notes', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 40,
    },
    {
      code: 'AUDIO_CALL_READY',
      label: 'Audio Call Ready',
      description: 'Both sides can join the audio room.',
      category: 'consultation',
      defaultFlags: { triggers_audio_call: true },
      defaultActionsProvider: [
        { action: 'join_call', label: 'Join audio call', targetStatus: 'audio_call_active', style: 'primary' },
      ],
      defaultActionsPatient: [
        { action: 'join_call', label: 'Join audio call', targetStatus: 'audio_call_active', style: 'primary' },
      ],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 31,
    },
    {
      code: 'AUDIO_CALL_ACTIVE',
      label: 'In Audio Call',
      description: 'Audio consultation is in progress.',
      category: 'consultation',
      defaultFlags: { triggers_audio_call: true },
      defaultActionsProvider: [
        { action: 'end_call', label: 'End call & write notes', targetStatus: 'writing_notes', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 41,
    },
    {
      code: 'WAITING_ROOM',
      label: 'Waiting Room',
      description: 'Member is in the virtual waiting room before the provider joins.',
      category: 'consultation',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'start_call', label: 'Start consultation', targetStatus: 'video_call_active', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 25,
    },
    {
      code: 'IN_PROGRESS_OFFICE',
      label: 'In Progress (Office)',
      description: 'Member is at the office, consultation underway.',
      category: 'consultation',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'complete', label: 'Mark as done', targetStatus: 'writing_notes', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 35,
    },
    {
      code: 'WRITING_NOTES',
      label: 'Writing Notes',
      description: 'Provider is writing clinical notes / prescription after the consultation.',
      category: 'consultation',
      defaultFlags: { requires_content: 'care_notes' },
      defaultActionsProvider: [
        { action: 'submit_notes', label: 'Submit notes', targetStatus: 'completed', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 50,
    },

    // ── Home visit ─────────────────────────────────────────────────────────
    {
      code: 'PROVIDER_TRAVELLING',
      label: 'Provider En Route',
      description: 'Provider has left and is travelling to the member address.',
      category: 'home_visit',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'arrived', label: 'I have arrived', targetStatus: 'provider_arrived', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 30,
    },
    {
      code: 'PROVIDER_ARRIVED',
      label: 'Provider Arrived',
      description: 'Provider is at the member location, service starting.',
      category: 'home_visit',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'complete', label: 'Service completed', targetStatus: 'completed', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 40,
    },

    // ── Lab / sample collection ────────────────────────────────────────────
    {
      code: 'SAMPLE_COLLECTED',
      label: 'Sample Collected',
      description: 'Biological sample collected from member.',
      category: 'lab',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'send_to_lab', label: 'Send to lab', targetStatus: 'processing', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 30,
    },
    {
      code: 'PROCESSING',
      label: 'Processing',
      description: 'Lab is analysing the sample.',
      category: 'lab',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'results_ready', label: 'Upload results', targetStatus: 'results_ready', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 40,
    },
    {
      code: 'RESULTS_READY',
      label: 'Results Ready',
      description: 'Lab results uploaded and shared with the member.',
      category: 'lab',
      defaultFlags: { requires_content: 'lab_result' },
      defaultActionsProvider: [
        { action: 'complete', label: 'Mark as complete', targetStatus: 'completed', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 50,
    },

    // ── Delivery / order ───────────────────────────────────────────────────
    {
      code: 'ORDER_CONFIRMED',
      label: 'Order Confirmed',
      description: 'Order received and confirmed by provider.',
      category: 'delivery',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'prepare', label: 'Start preparing', targetStatus: 'preparing', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 20,
    },
    {
      code: 'PREPARING',
      label: 'Preparing',
      description: 'Provider is preparing the order.',
      category: 'delivery',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'ready_pickup', label: 'Ready for pickup', targetStatus: 'ready_for_pickup', style: 'primary' },
        { action: 'dispatch', label: 'Out for delivery', targetStatus: 'out_for_delivery', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 30,
    },
    {
      code: 'READY_FOR_PICKUP',
      label: 'Ready for Pickup',
      description: 'Order ready at the provider location for collection.',
      category: 'delivery',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'complete', label: 'Confirm pickup', targetStatus: 'completed', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 40,
    },
    {
      code: 'OUT_FOR_DELIVERY',
      label: 'Out for Delivery',
      description: 'Order is on the way to the member.',
      category: 'delivery',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'delivered', label: 'Mark as delivered', targetStatus: 'completed', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 50,
    },
    {
      code: 'DISPATCHED',
      label: 'Dispatched',
      description: 'Specimen or item dispatched to external lab or address.',
      category: 'lab',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'confirm_receipt', label: 'Confirm receipt', targetStatus: 'processing', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 35,
    },

    // ── Emergency / ambulance ──────────────────────────────────────────────
    {
      code: 'EN_ROUTE',
      label: 'En Route',
      description: 'Emergency responder is on the way to the scene.',
      category: 'emergency',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'on_scene', label: 'Arrived on scene', targetStatus: 'on_scene', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 30,
    },
    {
      code: 'ON_SCENE',
      label: 'On Scene',
      description: 'Responder has arrived and is attending to the patient.',
      category: 'emergency',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'transport', label: 'Transporting to facility', targetStatus: 'transporting', style: 'primary' },
        { action: 'complete', label: 'Resolved on scene', targetStatus: 'completed', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 40,
    },
    {
      code: 'TRANSPORTING',
      label: 'Transporting',
      description: 'Patient being transported to a medical facility.',
      category: 'emergency',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'complete', label: 'Arrived at facility', targetStatus: 'completed', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 50,
    },

    // ── Therapy / session ──────────────────────────────────────────────────
    {
      code: 'SESSION_IN_PROGRESS',
      label: 'Session In Progress',
      description: 'Therapy / rehab / care session currently active.',
      category: 'consultation',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'complete', label: 'End session', targetStatus: 'session_complete', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 35,
    },
    {
      code: 'SESSION_COMPLETE',
      label: 'Session Complete',
      description: 'Session ended — notes or follow-up may be required.',
      category: 'consultation',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'complete', label: 'Mark as completed', targetStatus: 'completed', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 60,
    },

    // ── Enhanced emergency / ambulance ────────────────────────────────────────
    {
      code: 'DISPATCH_REQUESTED',
      label: 'Dispatch Requested',
      description: 'Emergency call received; dispatcher assigning responder.',
      category: 'emergency',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'dispatch', label: 'Dispatch responder', targetStatus: 'en_route', style: 'primary' },
        { action: 'cancel', label: 'Cancel call', targetStatus: 'cancelled', style: 'danger' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 15,
    },
    {
      code: 'TRIAGE',
      label: 'Triaging Patient',
      description: 'Responder assessing injury/illness severity on scene.',
      category: 'emergency',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'transport', label: 'Transport to facility', targetStatus: 'transporting', style: 'primary' },
        { action: 'treat_scene', label: 'Treat on scene', targetStatus: 'treating_on_scene', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 42,
    },
    {
      code: 'TREATING_ON_SCENE',
      label: 'Treating On Scene',
      description: 'Patient being treated at the incident location without transport.',
      category: 'emergency',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'complete', label: 'Treatment complete', targetStatus: 'completed', style: 'primary' },
        { action: 'transport', label: 'Now transporting', targetStatus: 'transporting', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 48,
    },
    {
      code: 'FACILITY_HANDOFF',
      label: 'Handed Off to Facility',
      description: 'Patient transferred to hospital / clinic staff.',
      category: 'emergency',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'complete', label: 'Handoff confirmed', targetStatus: 'completed', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 55,
    },

    // ── Recurrent / rehabilitation / programme ─────────────────────────────────
    {
      code: 'INTAKE_ASSESSMENT',
      label: 'Intake Assessment',
      description: 'Initial evaluation to design the care or rehab programme.',
      category: 'recurrent',
      defaultFlags: { requires_content: 'care_notes' },
      defaultActionsProvider: [
        { action: 'create_protocol', label: 'Create care protocol', targetStatus: 'protocol_created', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 20,
    },
    {
      code: 'PROTOCOL_CREATED',
      label: 'Protocol Created',
      description: 'Care plan / rehab protocol designed and ready to start.',
      category: 'recurrent',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'schedule_session', label: 'Schedule first session', targetStatus: 'session_scheduled', style: 'primary' },
      ],
      defaultActionsPatient: [
        { action: 'cancel', label: 'Cancel programme', targetStatus: 'cancelled', style: 'danger' },
      ],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 25,
    },
    {
      code: 'SESSION_SCHEDULED',
      label: 'Session Scheduled',
      description: 'Next session date & time confirmed with the patient.',
      category: 'recurrent',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'start_session', label: 'Start session', targetStatus: 'session_in_progress', style: 'primary' },
      ],
      defaultActionsPatient: [
        { action: 'cancel', label: 'Cancel session', targetStatus: 'cancelled', style: 'danger' },
      ],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 30,
    },
    {
      code: 'SESSION_NOTES_PENDING',
      label: 'Session Notes Pending',
      description: 'Session done — provider must submit notes before closing.',
      category: 'recurrent',
      defaultFlags: { requires_content: 'care_notes' },
      defaultActionsProvider: [
        { action: 'submit_notes', label: 'Submit session notes', targetStatus: 'session_complete', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 55,
    },
    {
      code: 'DISCHARGE_ASSESSMENT',
      label: 'Discharge Assessment',
      description: 'Final evaluation before formally closing the programme.',
      category: 'recurrent',
      defaultFlags: { requires_content: 'care_notes' },
      defaultActionsProvider: [
        { action: 'discharge', label: 'Discharge patient', targetStatus: 'discharged', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 70,
    },
    {
      code: 'DISCHARGED',
      label: 'Discharged',
      description: 'Programme successfully completed; patient formally discharged.',
      category: 'recurrent',
      defaultFlags: {},
      defaultActionsProvider: [],
      defaultActionsPatient: [],
      isTerminal: true,
      isCancellation: false,
      sortOrder: 810,
    },
    {
      code: 'PROGRAM_SUSPENDED',
      label: 'Programme Suspended',
      description: 'Programme paused due to patient request or medical hold.',
      category: 'recurrent',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'resume', label: 'Resume programme', targetStatus: 'session_scheduled', style: 'primary' },
        { action: 'close', label: 'Close programme', targetStatus: 'cancelled', style: 'danger' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 75,
    },

    // ── Dental multi-visit treatment ───────────────────────────────────────────
    {
      code: 'INITIAL_EXAM',
      label: 'Initial Examination',
      description: 'Dentist performs oral exam and takes X-rays if needed.',
      category: 'dental',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'plan', label: 'Create treatment plan', targetStatus: 'treatment_planned', style: 'primary' },
        { action: 'complete', label: 'No further action', targetStatus: 'completed', style: 'secondary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 20,
    },
    {
      code: 'TREATMENT_PLANNED',
      label: 'Treatment Planned',
      description: 'Treatment plan created — patient has reviewed and agreed.',
      category: 'dental',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'start', label: 'Begin procedure', targetStatus: 'procedure_in_progress', style: 'primary' },
      ],
      defaultActionsPatient: [
        { action: 'cancel', label: 'Decline treatment', targetStatus: 'cancelled', style: 'danger' },
      ],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 30,
    },
    {
      code: 'PROCEDURE_IN_PROGRESS',
      label: 'Procedure In Progress',
      description: 'Dental procedure currently underway.',
      category: 'dental',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'post_care', label: 'Procedure done — give post-care advice', targetStatus: 'post_care_given', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 40,
    },
    {
      code: 'POST_CARE_GIVEN',
      label: 'Post-Care Advice Given',
      description: 'Post-procedure instructions shared with the patient.',
      category: 'dental',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'schedule_followup', label: 'Schedule follow-up', targetStatus: 'follow_up_scheduled', style: 'primary' },
        { action: 'complete', label: 'Treatment complete', targetStatus: 'treatment_complete', style: 'secondary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 50,
    },
    {
      code: 'FOLLOW_UP_SCHEDULED',
      label: 'Follow-Up Scheduled',
      description: 'Next appointment booked to verify healing or continue treatment.',
      category: 'dental',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'start', label: 'Start follow-up visit', targetStatus: 'procedure_in_progress', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 60,
    },
    {
      code: 'TREATMENT_COMPLETE',
      label: 'Treatment Complete',
      description: 'All planned dental work finished; case closed.',
      category: 'dental',
      defaultFlags: {},
      defaultActionsProvider: [],
      defaultActionsPatient: [],
      isTerminal: true,
      isCancellation: false,
      sortOrder: 820,
    },

    // ── Nutrition / coaching ───────────────────────────────────────────────────
    {
      code: 'NUTRITION_ASSESSMENT',
      label: 'Nutritional Assessment',
      description: 'Dietitian collects dietary history, goals, and biometrics.',
      category: 'nutrition',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'create_plan', label: 'Create meal plan', targetStatus: 'meal_plan_created', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 20,
    },
    {
      code: 'MEAL_PLAN_CREATED',
      label: 'Meal Plan Created',
      description: 'Personalised nutrition plan drafted and ready for delivery.',
      category: 'nutrition',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'deliver', label: 'Share plan with patient', targetStatus: 'plan_delivered', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 30,
    },
    {
      code: 'PLAN_DELIVERED',
      label: 'Plan Delivered',
      description: 'Patient has received their nutrition plan.',
      category: 'nutrition',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'review', label: 'Schedule progress review', targetStatus: 'progress_review', style: 'primary' },
        { action: 'complete', label: 'Close case', targetStatus: 'completed', style: 'secondary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 40,
    },
    {
      code: 'PROGRESS_REVIEW',
      label: 'Progress Review',
      description: 'Follow-up session to track adherence and adjust the plan.',
      category: 'nutrition',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'adjust', label: 'Adjust plan', targetStatus: 'meal_plan_created', style: 'primary' },
        { action: 'goal_achieved', label: 'Goal achieved', targetStatus: 'goal_achieved', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 50,
    },
    {
      code: 'GOAL_ACHIEVED',
      label: 'Goal Achieved',
      description: 'Patient has reached their nutritional / health goal.',
      category: 'nutrition',
      defaultFlags: {},
      defaultActionsProvider: [],
      defaultActionsPatient: [],
      isTerminal: true,
      isCancellation: false,
      sortOrder: 830,
    },

    // ── Vaccination / immunisation ─────────────────────────────────────────────
    {
      code: 'PRE_VACCINATION_CHECK',
      label: 'Pre-Vaccination Check',
      description: 'Nurse reviews contraindications and confirms consent.',
      category: 'vaccination',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'administer', label: 'Administer vaccine', targetStatus: 'vaccine_administered', style: 'primary' },
        { action: 'defer', label: 'Defer vaccination', targetStatus: 'cancelled', style: 'secondary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 20,
    },
    {
      code: 'VACCINE_ADMINISTERED',
      label: 'Vaccine Administered',
      description: 'Injection given; observation period begins.',
      category: 'vaccination',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'start_obs', label: 'Start observation', targetStatus: 'observation_period', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 30,
    },
    {
      code: 'OBSERVATION_PERIOD',
      label: 'Observation Period',
      description: 'Patient monitored for adverse reactions post-injection.',
      category: 'vaccination',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'clear', label: 'Clear — no reaction', targetStatus: 'vaccination_complete', style: 'primary' },
        { action: 'reaction', label: 'Adverse reaction observed', targetStatus: 'reaction_observed', style: 'danger' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 40,
    },
    {
      code: 'REACTION_OBSERVED',
      label: 'Adverse Reaction',
      description: 'Patient showing a reaction; provider managing on site.',
      category: 'vaccination',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'resolve', label: 'Reaction resolved', targetStatus: 'vaccination_complete', style: 'primary' },
        { action: 'refer', label: 'Refer to emergency', targetStatus: 'completed', style: 'danger' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 45,
    },
    {
      code: 'VACCINATION_COMPLETE',
      label: 'Vaccination Complete',
      description: 'Vaccine administered and observation period passed without issues.',
      category: 'vaccination',
      defaultFlags: {},
      defaultActionsProvider: [],
      defaultActionsPatient: [],
      isTerminal: true,
      isCancellation: false,
      sortOrder: 840,
    },

    // ── Corporate health screening ─────────────────────────────────────────────
    {
      code: 'SCREENING_SCHEDULED',
      label: 'Screening Scheduled',
      description: 'Corporate health screening date confirmed with the company.',
      category: 'corporate',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'start', label: 'Start screening', targetStatus: 'screening_in_progress', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 20,
    },
    {
      code: 'SCREENING_IN_PROGRESS',
      label: 'Screening In Progress',
      description: 'Employees being screened — biometrics, ECG, blood draw, etc.',
      category: 'corporate',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'generate_reports', label: 'Generate reports', targetStatus: 'reports_generated', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 30,
    },
    {
      code: 'REPORTS_GENERATED',
      label: 'Reports Generated',
      description: 'Individual and aggregate screening reports ready.',
      category: 'corporate',
      defaultFlags: { requires_content: 'lab_result' },
      defaultActionsProvider: [
        { action: 'deliver', label: 'Deliver reports to company', targetStatus: 'reports_delivered', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 40,
    },
    {
      code: 'REPORTS_DELIVERED',
      label: 'Reports Delivered',
      description: 'Reports handed over to the corporate admin.',
      category: 'corporate',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'complete', label: 'Close contract', targetStatus: 'completed', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 50,
    },

    // ── Pharmacy prescription fulfilment ──────────────────────────────────────
    {
      code: 'RX_RECEIVED',
      label: 'Prescription Received',
      description: 'Pharmacist has the prescription (physical or e-prescription).',
      category: 'pharmacy',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'verify', label: 'Verify prescription', targetStatus: 'rx_verified', style: 'primary' },
        { action: 'reject', label: 'Reject invalid Rx', targetStatus: 'cancelled', style: 'danger' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 20,
    },
    {
      code: 'RX_VERIFIED',
      label: 'Prescription Verified',
      description: 'Prescription is valid; preparing the medication.',
      category: 'pharmacy',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'ready', label: 'Medication ready', targetStatus: 'medication_ready', style: 'primary' },
        { action: 'substitute', label: 'Propose substitution', targetStatus: 'substitution_proposed', style: 'secondary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 30,
    },
    {
      code: 'SUBSTITUTION_PROPOSED',
      label: 'Substitution Proposed',
      description: 'Pharmacist suggests a generic or equivalent — awaiting patient consent.',
      category: 'pharmacy',
      defaultFlags: {},
      defaultActionsProvider: [],
      defaultActionsPatient: [
        { action: 'accept', label: 'Accept substitution', targetStatus: 'medication_ready', style: 'primary' },
        { action: 'decline', label: 'Decline — keep original', targetStatus: 'rx_verified', style: 'secondary' },
      ],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 35,
    },
    {
      code: 'MEDICATION_READY',
      label: 'Medication Ready',
      description: 'Medication prepared and awaiting patient collection or dispatch.',
      category: 'pharmacy',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'dispense', label: 'Dispense medication', targetStatus: 'dispensed', style: 'primary' },
        { action: 'deliver', label: 'Send for delivery', targetStatus: 'out_for_delivery', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 40,
    },
    {
      code: 'DISPENSED',
      label: 'Dispensed',
      description: 'Medication handed to the patient or their representative.',
      category: 'pharmacy',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'complete', label: 'Complete order', targetStatus: 'completed', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 50,
    },

    // ── Mental health / therapy ────────────────────────────────────────────────
    {
      code: 'CRISIS_ASSESSMENT',
      label: 'Crisis Assessment',
      description: 'Urgent mental health triage — risk level and immediate care plan determined.',
      category: 'mental_health',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'schedule', label: 'Schedule therapy sessions', targetStatus: 'session_scheduled', style: 'primary' },
        { action: 'refer', label: 'Refer to inpatient', targetStatus: 'completed', style: 'danger' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 20,
    },
    {
      code: 'THERAPY_SESSION_ACTIVE',
      label: 'Therapy Session Active',
      description: 'Ongoing therapy session (in-person, video, or audio).',
      category: 'mental_health',
      defaultFlags: { triggers_video_call: true },
      defaultActionsProvider: [
        { action: 'end', label: 'End session — write notes', targetStatus: 'session_notes_pending', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 35,
    },
    {
      code: 'MEDICATION_REVIEW',
      label: 'Medication Review',
      description: 'Psychiatrist reviews current medication and adjusts if needed.',
      category: 'mental_health',
      defaultFlags: { requires_prescription: true },
      defaultActionsProvider: [
        { action: 'complete', label: 'Review complete', targetStatus: 'progress_evaluation', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 55,
    },
    {
      code: 'PROGRESS_EVALUATION',
      label: 'Progress Evaluation',
      description: 'Formal outcome measurement (PHQ-9, GAD-7, etc.) and decision on continuation.',
      category: 'mental_health',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'continue', label: 'Continue programme', targetStatus: 'session_scheduled', style: 'primary' },
        { action: 'discharge', label: 'Discharge patient', targetStatus: 'discharged', style: 'secondary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 65,
    },

    // ── Health shop / order ────────────────────────────────────────────────────
    {
      code: 'ORDER_PLACED',
      label: 'Order Placed',
      description: 'Patient has placed a health shop order — awaiting provider confirmation.',
      category: 'shop',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'confirm', label: 'Confirm order', targetStatus: 'order_confirmed', style: 'primary' },
        { action: 'cancel', label: 'Reject order', targetStatus: 'order_cancelled', style: 'danger' },
      ],
      defaultActionsPatient: [
        { action: 'cancel', label: 'Cancel order', targetStatus: 'order_cancelled', style: 'danger' },
      ],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 10,
    },
    {
      code: 'PRESCRIPTION_VALIDATION',
      label: 'Prescription Validation',
      description: 'Provider checking an active prescription before releasing controlled items.',
      category: 'shop',
      defaultFlags: { requires_prescription: true },
      defaultActionsProvider: [
        { action: 'validate', label: 'Prescription valid — proceed', targetStatus: 'order_confirmed', style: 'primary' },
        { action: 'reject', label: 'Invalid prescription', targetStatus: 'order_cancelled', style: 'danger' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 15,
    },
    {
      code: 'PAYMENT_CONFIRMED',
      label: 'Payment Confirmed',
      description: 'Health Credit payment deducted; fulfilment can begin.',
      category: 'shop',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'prepare', label: 'Start preparing', targetStatus: 'preparing', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 22,
    },
    {
      code: 'ORDER_CANCELLED',
      label: 'Order Cancelled',
      description: 'Order cancelled by patient or rejected by provider.',
      category: 'shop',
      defaultFlags: {},
      defaultActionsProvider: [],
      defaultActionsPatient: [],
      isTerminal: true,
      isCancellation: true,
      sortOrder: 950,
    },
    {
      code: 'ORDER_REFUNDED',
      label: 'Order Refunded',
      description: 'Health Credit refunded to patient wallet.',
      category: 'shop',
      defaultFlags: {},
      defaultActionsProvider: [],
      defaultActionsPatient: [],
      isTerminal: true,
      isCancellation: false,
      sortOrder: 960,
    },

    // ── Pre-Authorization (Insurance) ─────────────────────────────────────
    {
      code: 'PRE_AUTH_SUBMITTED',
      label: 'Pre-Authorization Submitted',
      description: 'Insurance pre-authorization request filed — awaiting insurer response.',
      category: 'insurance',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'review', label: 'Begin review', targetStatus: 'pre_auth_under_review', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 970,
    },
    {
      code: 'PRE_AUTH_UNDER_REVIEW',
      label: 'Pre-Authorization Under Review',
      description: 'Insurance company is reviewing the pre-authorization request.',
      category: 'insurance',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'approve', label: 'Approve', targetStatus: 'pre_auth_approved', style: 'primary' },
        { action: 'deny', label: 'Deny', targetStatus: 'pre_auth_denied', style: 'danger' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 971,
    },
    {
      code: 'PRE_AUTH_APPROVED',
      label: 'Pre-Authorization Approved',
      description: 'Insurance approved — treatment or service can proceed.',
      category: 'insurance',
      defaultFlags: {},
      defaultActionsProvider: [
        { action: 'proceed', label: 'Proceed with service', targetStatus: 'confirmed', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 972,
    },
    {
      code: 'PRE_AUTH_DENIED',
      label: 'Pre-Authorization Denied',
      description: 'Insurance declined the pre-authorization — treatment cannot proceed under this claim.',
      category: 'insurance',
      defaultFlags: {},
      defaultActionsProvider: [],
      defaultActionsPatient: [],
      isTerminal: true,
      isCancellation: false,
      sortOrder: 973,
    },

    // ── Prescription flow ─────────────────────────────────────────────────
    {
      code: 'PRESCRIPTION_ISSUED',
      label: 'Prescription Issued',
      description: 'Provider has written and issued a prescription after the consultation.',
      category: 'consultation',
      defaultFlags: { requires_content: 'prescription' },
      defaultActionsProvider: [
        { action: 'complete', label: 'Close booking', targetStatus: 'completed', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 975,
    },

    // ── Domain 2: clinical scan/examine → result ─────────────────────────────
    // These step types carry defaultFlags so the engine enforces content
    // requirements automatically when a template uses them via stepType reference.
    {
      code: 'EXAM_COMPLETE',
      label: 'Examination Complete',
      description: 'Provider has finished the physical or diagnostic examination and must upload the report.',
      category: 'consultation',
      defaultFlags: { requires_content: 'report' },
      defaultActionsProvider: [
        { action: 'complete', label: 'Submit report & complete', targetStatus: 'completed', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 985,
    },
    {
      code: 'PRESCRIPTION_WRITTEN',
      label: 'Prescription Written',
      description: 'Optometrist (or provider) has written the eye / specialist prescription — must attach it.',
      category: 'consultation',
      defaultFlags: { requires_content: 'eye_prescription' },
      defaultActionsProvider: [
        { action: 'complete', label: 'Submit prescription & complete', targetStatus: 'completed', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 986,
    },
    {
      code: 'CARE_NOTES',
      label: 'Care Notes Required',
      description: 'Provider must write and attach clinical care notes before proceeding.',
      category: 'consultation',
      defaultFlags: { requires_content: 'care_notes' },
      defaultActionsProvider: [
        { action: 'submit', label: 'Submit care notes', targetStatus: 'completed', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 987,
    },
    {
      code: 'TREATMENT_PLAN_CREATED',
      label: 'Treatment / Exercise Plan Created',
      description: 'Physiotherapist (or provider) must attach the exercise or treatment plan before notifying the patient.',
      category: 'recurrent',
      defaultFlags: { requires_content: 'exercise_plan' },
      defaultActionsProvider: [
        { action: 'deliver', label: 'Send plan to patient', targetStatus: 'plan_delivered', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 988,
    },

    // ── Caregiver ─────────────────────────────────────────────────────────
    {
      code: 'PROGRAM_ASSESSMENT',
      label: 'Initial Program Assessment',
      description: 'First visit — provider assesses patient and designs treatment / care protocol.',
      category: 'recurrent',
      defaultFlags: { requires_content: 'care_notes' },
      defaultActionsProvider: [
        { action: 'create_protocol', label: 'Create care protocol', targetStatus: 'protocol_created', style: 'primary' },
      ],
      defaultActionsPatient: [],
      isTerminal: false,
      isCancellation: false,
      sortOrder: 980,
    },
  ]

  for (const step of steps) {
    const data = {
      label: step.label,
      description: step.description,
      category: step.category,
      defaultFlags: step.defaultFlags as any,
      defaultActionsProvider: step.defaultActionsProvider as any,
      defaultActionsPatient: step.defaultActionsPatient as any,
      isTerminal: step.isTerminal,
      isCancellation: step.isCancellation,
      sortOrder: step.sortOrder,
    }
    await prisma.workflowStepType.upsert({
      where: { code: step.code },
      update: data,
      create: { code: step.code, ...data },
    })
  }

  console.log(`✅ Seeded ${steps.length} workflow step types`)
}
