/**
 * Seed 58 — Health Shop categories & products
 *
 * Creates ~30 inventory items spread across the new extended category set.
 * Uses upsert-by-name+provider to be idempotent.
 */

import { PrismaClient } from '@prisma/client'

export async function seedHealthShopCategories(prisma: PrismaClient) {
  console.log('  Seeding health shop categories & products...')

  const items = [
    // ── Prescription Medicines (Rx) ──────────────────────────────────────────
    {
      providerUserId: 'PHARM001',
      providerType: 'PHARMACIST',
      name: 'Metformin 500mg',
      category: 'prescription_medicines',
      description: 'First-line oral medication for type 2 diabetes. 30 tablets per strip.',
      price: 95,
      currency: 'MUR',
      quantity: 120,
      minStockAlert: 10,
      inStock: true,
      isFeatured: true,
      requiresPrescription: true,
      unitOfMeasure: 'strip',
      strength: '500mg',
      dosageForm: 'tablet',
    },
    {
      providerUserId: 'PHARM001',
      providerType: 'PHARMACIST',
      name: 'Atorvastatin 10mg',
      category: 'prescription_medicines',
      description: 'Statin medication for lowering LDL cholesterol. 30 tablets per box.',
      price: 145,
      currency: 'MUR',
      quantity: 80,
      minStockAlert: 10,
      inStock: true,
      isFeatured: false,
      requiresPrescription: true,
      unitOfMeasure: 'box',
      strength: '10mg',
      dosageForm: 'tablet',
    },
    {
      providerUserId: 'PHARM001',
      providerType: 'PHARMACIST',
      name: 'Amlodipine 5mg',
      category: 'prescription_medicines',
      description: 'Calcium channel blocker for hypertension. 30 tablets per box.',
      price: 110,
      currency: 'MUR',
      quantity: 100,
      minStockAlert: 10,
      inStock: true,
      isFeatured: false,
      requiresPrescription: true,
      unitOfMeasure: 'box',
      strength: '5mg',
      dosageForm: 'tablet',
    },
    {
      providerUserId: 'PHARM001',
      providerType: 'PHARMACIST',
      name: 'Salbutamol Inhaler 100mcg',
      category: 'prescription_medicines',
      description: 'Bronchodilator inhaler for asthma relief. 200 doses per inhaler.',
      price: 220,
      currency: 'MUR',
      quantity: 60,
      minStockAlert: 8,
      inStock: true,
      isFeatured: true,
      requiresPrescription: true,
      unitOfMeasure: 'unit',
      strength: '100mcg',
      dosageForm: 'inhaler',
    },
    {
      providerUserId: 'PHARM001',
      providerType: 'PHARMACIST',
      name: 'Omeprazole 20mg',
      category: 'prescription_medicines',
      description: 'Proton pump inhibitor for acid reflux and GERD. 14 capsules per box.',
      price: 130,
      currency: 'MUR',
      quantity: 90,
      minStockAlert: 10,
      inStock: true,
      isFeatured: false,
      requiresPrescription: true,
      unitOfMeasure: 'box',
      strength: '20mg',
      dosageForm: 'capsule',
    },
    {
      providerUserId: 'PHARM001',
      providerType: 'PHARMACIST',
      name: 'Levothyroxine 50mcg',
      category: 'prescription_medicines',
      description: 'Thyroid hormone replacement therapy. 30 tablets per box.',
      price: 115,
      currency: 'MUR',
      quantity: 70,
      minStockAlert: 8,
      inStock: true,
      isFeatured: false,
      requiresPrescription: true,
      unitOfMeasure: 'box',
      strength: '50mcg',
      dosageForm: 'tablet',
    },
    {
      providerUserId: 'PHARM001',
      providerType: 'PHARMACIST',
      name: 'Sertraline 50mg',
      category: 'prescription_medicines',
      description: 'SSRI antidepressant for depression and anxiety disorders. 30 tablets.',
      price: 180,
      currency: 'MUR',
      quantity: 55,
      minStockAlert: 8,
      inStock: true,
      isFeatured: false,
      requiresPrescription: true,
      unitOfMeasure: 'box',
      strength: '50mg',
      dosageForm: 'tablet',
    },
    {
      providerUserId: 'PHARM001',
      providerType: 'PHARMACIST',
      name: 'Lisinopril 10mg',
      category: 'prescription_medicines',
      description: 'ACE inhibitor for hypertension and heart failure. 30 tablets.',
      price: 125,
      currency: 'MUR',
      quantity: 85,
      minStockAlert: 10,
      inStock: true,
      isFeatured: false,
      requiresPrescription: true,
      unitOfMeasure: 'box',
      strength: '10mg',
      dosageForm: 'tablet',
    },
    {
      providerUserId: 'PHARM001',
      providerType: 'PHARMACIST',
      name: 'Warfarin 5mg',
      category: 'prescription_medicines',
      description: 'Anticoagulant for prevention of blood clots. 30 tablets. Requires regular INR monitoring.',
      price: 95,
      currency: 'MUR',
      quantity: 50,
      minStockAlert: 5,
      inStock: true,
      isFeatured: false,
      requiresPrescription: true,
      unitOfMeasure: 'box',
      strength: '5mg',
      dosageForm: 'tablet',
    },
    {
      providerUserId: 'PHARM001',
      providerType: 'PHARMACIST',
      name: 'Prednisone 5mg',
      category: 'prescription_medicines',
      description: 'Corticosteroid for inflammatory conditions. 20 tablets per box.',
      price: 85,
      currency: 'MUR',
      quantity: 65,
      minStockAlert: 8,
      inStock: true,
      isFeatured: false,
      requiresPrescription: true,
      unitOfMeasure: 'box',
      strength: '5mg',
      dosageForm: 'tablet',
    },

    // ── OTC Medicines ─────────────────────────────────────────────────────────
    {
      providerUserId: 'PHARM001',
      providerType: 'PHARMACIST',
      name: 'Ibuprofen 400mg',
      category: 'otc_medicines',
      description: 'NSAID for pain relief, fever, and inflammation. 20 tablets per box.',
      price: 55,
      currency: 'MUR',
      quantity: 150,
      minStockAlert: 15,
      inStock: true,
      isFeatured: true,
      requiresPrescription: false,
      unitOfMeasure: 'box',
      strength: '400mg',
      dosageForm: 'tablet',
    },
    {
      providerUserId: 'PHARM001',
      providerType: 'PHARMACIST',
      name: 'Cetirizine 10mg',
      category: 'otc_medicines',
      description: 'Non-drowsy antihistamine for allergy relief. 10 tablets per box.',
      price: 45,
      currency: 'MUR',
      quantity: 130,
      minStockAlert: 10,
      inStock: true,
      isFeatured: false,
      requiresPrescription: false,
      unitOfMeasure: 'box',
      strength: '10mg',
      dosageForm: 'tablet',
    },
    {
      providerUserId: 'PHARM001',
      providerType: 'PHARMACIST',
      name: 'Loperamide 2mg',
      category: 'otc_medicines',
      description: 'Fast-acting anti-diarrhoeal. 6 capsules per pack.',
      price: 40,
      currency: 'MUR',
      quantity: 110,
      minStockAlert: 10,
      inStock: true,
      isFeatured: false,
      requiresPrescription: false,
      unitOfMeasure: 'pack',
      strength: '2mg',
      dosageForm: 'capsule',
    },
    {
      providerUserId: 'PHARM001',
      providerType: 'PHARMACIST',
      name: 'Oral Rehydration Salts',
      category: 'otc_medicines',
      description: 'WHO-formula electrolyte sachets for dehydration. 10 sachets per box.',
      price: 35,
      currency: 'MUR',
      quantity: 200,
      minStockAlert: 20,
      inStock: true,
      isFeatured: false,
      requiresPrescription: false,
      unitOfMeasure: 'box',
      strength: undefined,
      dosageForm: 'sachet',
    },
    {
      providerUserId: 'PHARM001',
      providerType: 'PHARMACIST',
      name: 'Chlorhexidine Mouthwash 0.2%',
      category: 'otc_medicines',
      description: 'Antiseptic mouthwash for oral hygiene and gingivitis. 300ml bottle.',
      price: 75,
      currency: 'MUR',
      quantity: 90,
      minStockAlert: 8,
      inStock: true,
      isFeatured: false,
      requiresPrescription: false,
      unitOfMeasure: 'bottle',
      strength: '0.2%',
      dosageForm: 'liquid',
    },

    // ── Fitness & Wellness ────────────────────────────────────────────────────
    {
      providerUserId: 'PHARM001',
      providerType: 'PHARMACIST',
      name: 'Whey Protein Isolate — Vanilla',
      category: 'fitness_wellness',
      description: 'High-quality whey protein for muscle recovery. 25g protein per serving. 1kg bag.',
      price: 850,
      currency: 'MUR',
      quantity: 50,
      minStockAlert: 5,
      inStock: true,
      isFeatured: true,
      requiresPrescription: false,
      unitOfMeasure: 'bag',
      strength: undefined,
      dosageForm: undefined,
    },
    {
      providerUserId: 'PHARM001',
      providerType: 'PHARMACIST',
      name: 'Creatine Monohydrate',
      category: 'fitness_wellness',
      description: 'Pure creatine for strength and performance. 300g tub.',
      price: 420,
      currency: 'MUR',
      quantity: 60,
      minStockAlert: 5,
      inStock: true,
      isFeatured: false,
      requiresPrescription: false,
      unitOfMeasure: 'tub',
      strength: undefined,
      dosageForm: undefined,
    },
    {
      providerUserId: 'PHARM001',
      providerType: 'PHARMACIST',
      name: 'Electrolyte Hydration Tabs',
      category: 'fitness_wellness',
      description: 'Sugar-free electrolyte tablets for active hydration. 20 tabs per tube.',
      price: 180,
      currency: 'MUR',
      quantity: 100,
      minStockAlert: 10,
      inStock: true,
      isFeatured: false,
      requiresPrescription: false,
      unitOfMeasure: 'tube',
      strength: undefined,
      dosageForm: undefined,
    },
    {
      providerUserId: 'PHARM001',
      providerType: 'PHARMACIST',
      name: 'Resistance Bands Set',
      category: 'fitness_wellness',
      description: 'Set of 5 latex resistance bands — light to extra-heavy. For home workouts.',
      price: 350,
      currency: 'MUR',
      quantity: 40,
      minStockAlert: 5,
      inStock: true,
      isFeatured: false,
      requiresPrescription: false,
      unitOfMeasure: 'set',
      strength: undefined,
      dosageForm: undefined,
    },
    {
      providerUserId: 'PHARM001',
      providerType: 'PHARMACIST',
      name: 'Foam Roller — Deep Tissue',
      category: 'fitness_wellness',
      description: 'High-density foam roller for muscle recovery and myofascial release. 60cm.',
      price: 280,
      currency: 'MUR',
      quantity: 30,
      minStockAlert: 5,
      inStock: true,
      isFeatured: false,
      requiresPrescription: false,
      unitOfMeasure: 'unit',
      strength: undefined,
      dosageForm: undefined,
    },

    // ── Beauty Care ───────────────────────────────────────────────────────────
    {
      providerUserId: 'PHARM001',
      providerType: 'PHARMACIST',
      name: 'SPF 50+ Sunscreen Gel',
      category: 'beauty_care',
      description: 'Broad-spectrum UVA/UVB protection. Lightweight, non-greasy. 75ml.',
      price: 195,
      currency: 'MUR',
      quantity: 80,
      minStockAlert: 8,
      inStock: true,
      isFeatured: true,
      requiresPrescription: false,
      unitOfMeasure: 'bottle',
      strength: 'SPF 50+',
      dosageForm: 'gel',
    },
    {
      providerUserId: 'PHARM001',
      providerType: 'PHARMACIST',
      name: 'Niacinamide 10% Face Serum',
      category: 'beauty_care',
      description: 'Brightening serum that minimises pores and evens skin tone. 30ml.',
      price: 320,
      currency: 'MUR',
      quantity: 60,
      minStockAlert: 5,
      inStock: true,
      isFeatured: false,
      requiresPrescription: false,
      unitOfMeasure: 'bottle',
      strength: '10%',
      dosageForm: 'serum',
    },
    {
      providerUserId: 'PHARM001',
      providerType: 'PHARMACIST',
      name: 'Hyaluronic Acid Moisturiser',
      category: 'beauty_care',
      description: 'Deep hydration moisturiser for all skin types. 50ml jar.',
      price: 260,
      currency: 'MUR',
      quantity: 70,
      minStockAlert: 5,
      inStock: true,
      isFeatured: false,
      requiresPrescription: false,
      unitOfMeasure: 'jar',
      strength: undefined,
      dosageForm: 'cream',
    },

    // ── Ayurveda & Wellness ───────────────────────────────────────────────────
    {
      providerUserId: 'PHARM001',
      providerType: 'PHARMACIST',
      name: 'Ashwagandha Root Extract 500mg',
      category: 'ayurveda',
      description: 'Adaptogenic herb for stress relief and energy. 60 capsules per bottle.',
      price: 290,
      currency: 'MUR',
      quantity: 75,
      minStockAlert: 8,
      inStock: true,
      isFeatured: true,
      requiresPrescription: false,
      unitOfMeasure: 'bottle',
      strength: '500mg',
      dosageForm: 'capsule',
    },
    {
      providerUserId: 'PHARM001',
      providerType: 'PHARMACIST',
      name: 'Triphala Churna',
      category: 'ayurveda',
      description: 'Traditional Ayurvedic blend of three fruits for digestive wellness. 200g powder.',
      price: 155,
      currency: 'MUR',
      quantity: 65,
      minStockAlert: 5,
      inStock: true,
      isFeatured: false,
      requiresPrescription: false,
      unitOfMeasure: 'bottle',
      strength: undefined,
      dosageForm: 'powder',
    },
    {
      providerUserId: 'PHARM001',
      providerType: 'PHARMACIST',
      name: 'Moringa Leaf Capsules 400mg',
      category: 'ayurveda',
      description: 'Nutrient-dense superfood supplement rich in vitamins and minerals. 90 capsules.',
      price: 210,
      currency: 'MUR',
      quantity: 80,
      minStockAlert: 5,
      inStock: true,
      isFeatured: false,
      requiresPrescription: false,
      unitOfMeasure: 'bottle',
      strength: '400mg',
      dosageForm: 'capsule',
    },

    // ── Medical Devices ───────────────────────────────────────────────────────
    {
      providerUserId: 'PHARM001',
      providerType: 'PHARMACIST',
      name: 'Digital Blood Pressure Monitor',
      category: 'medical_devices',
      description: 'Clinically validated upper arm blood pressure monitor with large display. Stores 60 readings.',
      price: 1250,
      currency: 'MUR',
      quantity: 25,
      minStockAlert: 3,
      inStock: true,
      isFeatured: true,
      requiresPrescription: false,
      unitOfMeasure: 'unit',
      strength: undefined,
      dosageForm: undefined,
    },
    {
      providerUserId: 'PHARM001',
      providerType: 'PHARMACIST',
      name: 'Pulse Oximeter',
      category: 'medical_devices',
      description: 'Fingertip pulse oximeter with OLED display for SpO2 and heart rate monitoring.',
      price: 380,
      currency: 'MUR',
      quantity: 40,
      minStockAlert: 5,
      inStock: true,
      isFeatured: false,
      requiresPrescription: false,
      unitOfMeasure: 'unit',
      strength: undefined,
      dosageForm: undefined,
    },
    {
      providerUserId: 'PHARM001',
      providerType: 'PHARMACIST',
      name: 'Digital Thermometer',
      category: 'medical_devices',
      description: 'Fast 10-second reading oral/rectal/underarm digital thermometer with memory recall.',
      price: 175,
      currency: 'MUR',
      quantity: 60,
      minStockAlert: 8,
      inStock: true,
      isFeatured: false,
      requiresPrescription: false,
      unitOfMeasure: 'unit',
      strength: undefined,
      dosageForm: undefined,
    },
    {
      providerUserId: 'PHARM001',
      providerType: 'PHARMACIST',
      name: 'Blood Glucose Test Strips (50s)',
      category: 'medical_devices',
      description: 'Compatible test strips for most standard glucometers. 50 strips per box.',
      price: 320,
      currency: 'MUR',
      quantity: 55,
      minStockAlert: 5,
      inStock: true,
      isFeatured: false,
      requiresPrescription: false,
      unitOfMeasure: 'box',
      strength: undefined,
      dosageForm: undefined,
    },
  ]

  let created = 0
  let skipped = 0

  for (const item of items) {
    try {
      const existing = await prisma.providerInventoryItem.findFirst({
        where: { providerUserId: item.providerUserId, name: item.name },
        select: { id: true },
      })

      if (existing) {
        skipped++
        continue
      }

      await prisma.providerInventoryItem.create({
        data: {
          providerUserId: item.providerUserId,
          providerType: item.providerType,
          name: item.name,
          category: item.category,
          description: item.description,
          price: item.price,
          currency: item.currency,
          quantity: item.quantity,
          minStockAlert: item.minStockAlert,
          inStock: item.inStock,
          isFeatured: item.isFeatured,
          requiresPrescription: item.requiresPrescription,
          unitOfMeasure: item.unitOfMeasure,
          ...(item.strength ? { strength: item.strength } : {}),
          ...(item.dosageForm ? { dosageForm: item.dosageForm } : {}),
        },
      })
      created++
    } catch (err) {
      console.warn(`  [58] Skipping "${item.name}":`, err instanceof Error ? err.message : String(err))
      skipped++
    }
  }

  console.log(`  [58] Health shop items: ${created} created, ${skipped} skipped`)
}
