#!/usr/bin/env bash
# scripts/setup-nginx.sh
# Run by CI/CD deploy step to configure nginx reverse proxy for mediwyz.com
# Usage: APP_DOMAIN=mediwyz.com ADMIN_EMAIL=admin@mediwyz.com bash scripts/setup-nginx.sh

set -e

DOMAIN="${APP_DOMAIN:-}"
ADMIN_EMAIL="${ADMIN_EMAIL:-admin@mediwyz.com}"

if [ -z "$DOMAIN" ]; then
  echo "APP_DOMAIN not set — skipping nginx setup"
  exit 0
fi

if ! command -v nginx >/dev/null 2>&1; then
  echo "nginx not installed — skipping nginx setup"
  exit 0
fi

echo "=== Configuring nginx for $DOMAIN ==="

CERT_DIR="/etc/letsencrypt/live/$DOMAIN"
HAS_CERT=0
[ -f "$CERT_DIR/fullchain.pem" ] && HAS_CERT=1

# Write nginx config
sudo tee /etc/nginx/sites-available/mediwyz > /dev/null << NGINXEOF
# MediWyz — nginx reverse proxy
# Auto-generated by scripts/setup-nginx.sh

server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN} www.${DOMAIN};

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
        client_max_body_size 50M;
    }

    location /socket.io/ {
        proxy_pass http://localhost:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection upgrade;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
    }
}
NGINXEOF

# If we already have a cert, add the HTTPS server block too
if [ "$HAS_CERT" = "1" ]; then
  sudo tee -a /etc/nginx/sites-available/mediwyz > /dev/null << HTTPSEOF

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ${DOMAIN} www.${DOMAIN};

    ssl_certificate     ${CERT_DIR}/fullchain.pem;
    ssl_certificate_key ${CERT_DIR}/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
        client_max_body_size 50M;
    }

    location /socket.io/ {
        proxy_pass http://localhost:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection upgrade;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
    }
}
HTTPSEOF
fi

sudo ln -sf /etc/nginx/sites-available/mediwyz /etc/nginx/sites-enabled/mediwyz
sudo rm -f /etc/nginx/sites-enabled/default 2>/dev/null || true

if sudo nginx -t 2>/dev/null; then
  sudo systemctl reload nginx && echo "nginx reloaded for $DOMAIN"
else
  echo "WARNING: nginx config test failed — check /etc/nginx/sites-available/mediwyz"
fi

# Obtain SSL cert if not yet present
if command -v certbot >/dev/null 2>&1 && [ "$HAS_CERT" = "0" ]; then
  echo "=== Requesting SSL certificate for $DOMAIN ==="
  sudo mkdir -p /var/www/html/.well-known/acme-challenge
  sudo certbot certonly --webroot -w /var/www/html \
    -d "$DOMAIN" -d "www.$DOMAIN" \
    --non-interactive --agree-tos \
    -m "$ADMIN_EMAIL" 2>&1 \
  && bash "$0" \
  || echo "WARNING: certbot failed — app accessible on HTTP only for now"
else
  echo "SSL cert already exists for $DOMAIN — reloading nginx"
  sudo systemctl reload nginx
fi
